# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\saleV3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1596, 832)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: #fff8f2;\n"
"outline:0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.CheckCountPB = QtWidgets.QPushButton(self.frame)
        self.CheckCountPB.setMinimumSize(QtCore.QSize(150, 35))
        self.CheckCountPB.setMaximumSize(QtCore.QSize(188, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.CheckCountPB.setFont(font)
        self.CheckCountPB.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    border:None;\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-repeat: no-repeat;\n"
"    margin-top: 5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color:#00aaff;\n"
"    color: rgb(170, 255, 255);\n"
"    padding-left:10px;\n"
"    border-radius:10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckCountPB.setIcon(icon1)
        self.CheckCountPB.setIconSize(QtCore.QSize(20, 20))
        self.CheckCountPB.setCheckable(True)
        self.CheckCountPB.setAutoExclusive(True)
        self.CheckCountPB.setObjectName("CheckCountPB")
        self.verticalLayout.addWidget(self.CheckCountPB)
        self.ProductSearchPB = QtWidgets.QPushButton(self.frame)
        self.ProductSearchPB.setMinimumSize(QtCore.QSize(128, 35))
        self.ProductSearchPB.setMaximumSize(QtCore.QSize(188, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ProductSearchPB.setFont(font)
        self.ProductSearchPB.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    border:None;\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-repeat: no-repeat;\n"
"    margin-top: 5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color:#00aaff;\n"
"    color: rgb(170, 255, 255);\n"
"    padding-left:10px;\n"
"    border-radius:10px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProductSearchPB.setIcon(icon2)
        self.ProductSearchPB.setIconSize(QtCore.QSize(20, 20))
        self.ProductSearchPB.setCheckable(True)
        self.ProductSearchPB.setAutoExclusive(True)
        self.ProductSearchPB.setObjectName("ProductSearchPB")
        self.verticalLayout.addWidget(self.ProductSearchPB)
        self.ProductSearchPB_2 = QtWidgets.QPushButton(self.frame)
        self.ProductSearchPB_2.setMinimumSize(QtCore.QSize(128, 35))
        self.ProductSearchPB_2.setMaximumSize(QtCore.QSize(188, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ProductSearchPB_2.setFont(font)
        self.ProductSearchPB_2.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    border:None;\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-repeat: no-repeat;\n"
"    margin-top: 5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color:#00aaff;\n"
"    color: rgb(170, 255, 255);\n"
"    padding-left:10px;\n"
"    border-radius:10px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:/Projects/TrillionTech/images/search-5-64.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProductSearchPB_2.setIcon(icon3)
        self.ProductSearchPB_2.setIconSize(QtCore.QSize(20, 20))
        self.ProductSearchPB_2.setCheckable(True)
        self.ProductSearchPB_2.setAutoExclusive(True)
        self.ProductSearchPB_2.setObjectName("ProductSearchPB_2")
        self.verticalLayout.addWidget(self.ProductSearchPB_2)
        spacerItem = QtWidgets.QSpacerItem(20, 648, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    outline:0px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox  {\n"
"    width: 100%;\n"
"    background:   #fff8f2;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setContentsMargins(-1, -1, -1, 15)
        self.gridLayout_9.setHorizontalSpacing(15)
        self.gridLayout_9.setVerticalSpacing(21)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background:   #fff8f2;")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background:   #fff8f2;")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 0, 5, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setMinimumSize(QtCore.QSize(120, 28))
        self.pushButton_3.setMaximumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#5cb0ff;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_9.addWidget(self.pushButton_3, 0, 9, 1, 1)
        self.credit_lineEdit_1_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.credit_lineEdit_1_4.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_4.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_4.setFont(font)
        self.credit_lineEdit_1_4.setObjectName("credit_lineEdit_1_4")
        self.gridLayout_9.addWidget(self.credit_lineEdit_1_4, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background:   #fff8f2;")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox_2.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_9.addWidget(self.comboBox_2, 0, 4, 1, 1)
        self.credit_lineEdit_1_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.credit_lineEdit_1_2.setEnabled(False)
        self.credit_lineEdit_1_2.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_2.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_2.setFont(font)
        self.credit_lineEdit_1_2.setObjectName("credit_lineEdit_1_2")
        self.gridLayout_9.addWidget(self.credit_lineEdit_1_2, 1, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 0, 1, 1)
        self.type_comboBox_1_1 = QtWidgets.QComboBox(self.groupBox_3)
        self.type_comboBox_1_1.setMinimumSize(QtCore.QSize(200, 30))
        self.type_comboBox_1_1.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.type_comboBox_1_1.setFont(font)
        self.type_comboBox_1_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.type_comboBox_1_1.setEditable(True)
        self.type_comboBox_1_1.setObjectName("type_comboBox_1_1")
        self.gridLayout_9.addWidget(self.type_comboBox_1_1, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background:   #fff8f2;")
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox_3.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_9.addWidget(self.comboBox_3, 0, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:   #fff8f2;")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 1, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:   #fff8f2;")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 10, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(120, 28))
        self.pushButton_7.setMaximumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#5cb0ff;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_9.addWidget(self.pushButton_7, 1, 9, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox_4.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_9.addWidget(self.comboBox_4, 0, 6, 1, 1)
        self.credit_lineEdit_1_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.credit_lineEdit_1_3.setEnabled(False)
        self.credit_lineEdit_1_3.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_3.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_3.setFont(font)
        self.credit_lineEdit_1_3.setObjectName("credit_lineEdit_1_3")
        self.gridLayout_9.addWidget(self.credit_lineEdit_1_3, 1, 6, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background:   #fff8f2;")
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 1, 5, 1, 1)
        self.credit_lineEdit_1_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.credit_lineEdit_1_5.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_5.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_5.setFont(font)
        self.credit_lineEdit_1_5.setObjectName("credit_lineEdit_1_5")
        self.gridLayout_9.addWidget(self.credit_lineEdit_1_5, 1, 4, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(1085, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("QHeaderView {\n"
"    border:1px;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"    border-radius:14px;\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    text-align:left;\n"
"}\n"
"\n"
"QTableWidget::Item{\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    color: black;\n"
"}")
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setRowCount(999)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(145)
        self.gridLayout_9.addWidget(self.tableWidget_2, 2, 2, 1, 8)
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background:   #fff8f2;")
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 1, 3, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#fff8f2;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_8.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 101))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox  {\n"
"    width: 100%;\n"
"    background:   #fff8f2;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setSpacing(24)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setMaximumSize(QtCore.QSize(77, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background:   #fff8f2;")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.dateEdit_5 = QtWidgets.QDateEdit(self.groupBox_2)
        self.dateEdit_5.setMinimumSize(QtCore.QSize(200, 30))
        self.dateEdit_5.setMaximumSize(QtCore.QSize(200, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.dateEdit_5.setFont(font)
        self.dateEdit_5.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.dateEdit_5.setCalendarPopup(True)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.horizontalLayout.addWidget(self.dateEdit_5)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background:   #fff8f2;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.type_comboBox_1_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.type_comboBox_1_3.setMinimumSize(QtCore.QSize(200, 30))
        self.type_comboBox_1_3.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.type_comboBox_1_3.setFont(font)
        self.type_comboBox_1_3.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.type_comboBox_1_3.setEditable(True)
        self.type_comboBox_1_3.setObjectName("type_comboBox_1_3")
        self.horizontalLayout.addWidget(self.type_comboBox_1_3)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background:   #fff8f2;\n"
" ")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.credit_lineEdit_1_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.credit_lineEdit_1_1.setEnabled(False)
        self.credit_lineEdit_1_1.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_1.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_1.setFont(font)
        self.credit_lineEdit_1_1.setObjectName("credit_lineEdit_1_1")
        self.horizontalLayout.addWidget(self.credit_lineEdit_1_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(120, 28))
        self.pushButton_2.setMaximumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#5cb0ff;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon7)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout_8.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#fff8f2;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_8.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox  {\n"
"    width: 100%;\n"
"    background:   #fff8f2;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(38)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.type_comboBox_1_0 = QtWidgets.QComboBox(self.groupBox)
        self.type_comboBox_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.type_comboBox_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.type_comboBox_1_0.setFont(font)
        self.type_comboBox_1_0.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.type_comboBox_1_0.setEditable(True)
        self.type_comboBox_1_0.setObjectName("type_comboBox_1_0")
        self.gridLayout_2.addWidget(self.type_comboBox_1_0, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background:   #fff8f2;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background:   #fff8f2;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background:   #fff8f2;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 3, 1, 1)
        self.supply_comboBox_1_0 = QtWidgets.QComboBox(self.groupBox)
        self.supply_comboBox_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.supply_comboBox_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.supply_comboBox_1_0.setFont(font)
        self.supply_comboBox_1_0.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.supply_comboBox_1_0.setEditable(True)
        self.supply_comboBox_1_0.setObjectName("supply_comboBox_1_0")
        self.gridLayout_2.addWidget(self.supply_comboBox_1_0, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(130, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:   #fff8f2;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 3, 1, 1)
        self.lot_num_lineEdit_1_0 = QtWidgets.QLineEdit(self.groupBox)
        self.lot_num_lineEdit_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.lot_num_lineEdit_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.lot_num_lineEdit_1_0.setFont(font)
        self.lot_num_lineEdit_1_0.setObjectName("lot_num_lineEdit_1_0")
        self.gridLayout_2.addWidget(self.lot_num_lineEdit_1_0, 1, 4, 1, 1)
        self.in_dateEdit_1_0 = QtWidgets.QDateEdit(self.groupBox)
        self.in_dateEdit_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.in_dateEdit_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.in_dateEdit_1_0.setFont(font)
        self.in_dateEdit_1_0.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.in_dateEdit_1_0.setWrapping(False)
        self.in_dateEdit_1_0.setFrame(True)
        self.in_dateEdit_1_0.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.in_dateEdit_1_0.setAccelerated(True)
        self.in_dateEdit_1_0.setProperty("showGroupSeparator", True)
        self.in_dateEdit_1_0.setCalendarPopup(True)
        self.in_dateEdit_1_0.setObjectName("in_dateEdit_1_0")
        self.gridLayout_2.addWidget(self.in_dateEdit_1_0, 1, 2, 1, 1)
        self.credit_lineEdit_1_0 = QtWidgets.QLineEdit(self.groupBox)
        self.credit_lineEdit_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_0.setFont(font)
        self.credit_lineEdit_1_0.setObjectName("credit_lineEdit_1_0")
        self.gridLayout_2.addWidget(self.credit_lineEdit_1_0, 2, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background:   #fff8f2;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setMaximumSize(QtCore.QSize(130, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background:   #fff8f2;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 6, 1, 1)
        self.actual_count_spinBox_1_0 = QtWidgets.QSpinBox(self.groupBox)
        self.actual_count_spinBox_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.actual_count_spinBox_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.actual_count_spinBox_1_0.setFont(font)
        self.actual_count_spinBox_1_0.setMaximum(100000)
        self.actual_count_spinBox_1_0.setObjectName("actual_count_spinBox_1_0")
        self.gridLayout_2.addWidget(self.actual_count_spinBox_1_0, 3, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(141, 28))
        self.pushButton.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#fff8f2;\n"
"    border-color:#929799;\n"
"    border-style:solid;\n"
"    border-width:0.5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon8)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 4, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background:   #fff8f2;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 3, 1, 1)
        self.type_comboBox_1_2 = QtWidgets.QComboBox(self.groupBox)
        self.type_comboBox_1_2.setMinimumSize(QtCore.QSize(200, 30))
        self.type_comboBox_1_2.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.type_comboBox_1_2.setFont(font)
        self.type_comboBox_1_2.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.type_comboBox_1_2.setEditable(True)
        self.type_comboBox_1_2.setObjectName("type_comboBox_1_2")
        self.gridLayout_2.addWidget(self.type_comboBox_1_2, 4, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#fff8f2;\n"
"    border-color:#929799;\n"
"    border-style:solid;\n"
"    border-width:0.5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon9)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 5, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setMinimumSize(QtCore.QSize(330, 120))
        self.tableWidget.setMaximumSize(QtCore.QSize(280, 500))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView {\n"
"    border:1px;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"    border-radius:14px;\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    text-align:left;\n"
"\n"
"}\n"
"\n"
"QTableWidget::Item{\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    color: black;\n"
"}")
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 5, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 171))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 171))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_2.setStyleSheet("QFrame {\n"
"    width: 100%;\n"
"    background:   #fff8f2;\n"
"    border-radius: 5px;\n"
"    padding-bottom: 13px;\n"
"    box-shadow: 1px 1px 3px rgb(0 0 0 / 20%);\n"
"    padding-top:15px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_5.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.create_dateEdit_0_1 = QtWidgets.QDateEdit(self.frame_2)
        self.create_dateEdit_0_1.setMinimumSize(QtCore.QSize(201, 31))
        self.create_dateEdit_0_1.setMaximumSize(QtCore.QSize(171, 16777215))
        self.create_dateEdit_0_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.create_dateEdit_0_1.setCalendarPopup(True)
        self.create_dateEdit_0_1.setObjectName("create_dateEdit_0_1")
        self.gridLayout_5.addWidget(self.create_dateEdit_0_1, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setMaximumSize(QtCore.QSize(49, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 3, 1, 1)
        self.supply_comboBox_0_1 = QtWidgets.QComboBox(self.frame_2)
        self.supply_comboBox_0_1.setMinimumSize(QtCore.QSize(201, 31))
        self.supply_comboBox_0_1.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.supply_comboBox_0_1.setFont(font)
        self.supply_comboBox_0_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.supply_comboBox_0_1.setEditable(True)
        self.supply_comboBox_0_1.setObjectName("supply_comboBox_0_1")
        self.gridLayout_5.addWidget(self.supply_comboBox_0_1, 0, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setMaximumSize(QtCore.QSize(77, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 5, 1, 1)
        self.supply_comboBox_0_2 = QtWidgets.QComboBox(self.frame_2)
        self.supply_comboBox_0_2.setMinimumSize(QtCore.QSize(201, 31))
        self.supply_comboBox_0_2.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.supply_comboBox_0_2.setFont(font)
        self.supply_comboBox_0_2.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.supply_comboBox_0_2.setEditable(True)
        self.supply_comboBox_0_2.setObjectName("supply_comboBox_0_2")
        self.gridLayout_5.addWidget(self.supply_comboBox_0_2, 0, 6, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 8, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setMaximumSize(QtCore.QSize(77, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 1, 1, 1)
        self.lot_num_comboBox_0_1 = QtWidgets.QComboBox(self.frame_2)
        self.lot_num_comboBox_0_1.setMinimumSize(QtCore.QSize(201, 31))
        self.lot_num_comboBox_0_1.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.lot_num_comboBox_0_1.setFont(font)
        self.lot_num_comboBox_0_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.lot_num_comboBox_0_1.setEditable(True)
        self.lot_num_comboBox_0_1.setObjectName("lot_num_comboBox_0_1")
        self.gridLayout_5.addWidget(self.lot_num_comboBox_0_1, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setMaximumSize(QtCore.QSize(100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 3, 1, 1)
        self.status_comboBox_0_1 = QtWidgets.QComboBox(self.frame_2)
        self.status_comboBox_0_1.setMinimumSize(QtCore.QSize(201, 31))
        self.status_comboBox_0_1.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.status_comboBox_0_1.setFont(font)
        self.status_comboBox_0_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.status_comboBox_0_1.setEditable(True)
        self.status_comboBox_0_1.setObjectName("status_comboBox_0_1")
        self.gridLayout_5.addWidget(self.status_comboBox_0_1, 1, 4, 1, 1)
        self.again_pushButton_0_1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.again_pushButton_0_1.sizePolicy().hasHeightForWidth())
        self.again_pushButton_0_1.setSizePolicy(sizePolicy)
        self.again_pushButton_0_1.setMinimumSize(QtCore.QSize(100, 30))
        self.again_pushButton_0_1.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.again_pushButton_0_1.setFont(font)
        self.again_pushButton_0_1.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color:#ff6741;   \n"
"\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:10px;\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("D:/Projects/TrillionTech/images/redo-2-128.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.again_pushButton_0_1.setIcon(icon10)
        self.again_pushButton_0_1.setIconSize(QtCore.QSize(20, 20))
        self.again_pushButton_0_1.setCheckable(False)
        self.again_pushButton_0_1.setAutoRepeat(False)
        self.again_pushButton_0_1.setAutoExclusive(False)
        self.again_pushButton_0_1.setObjectName("again_pushButton_0_1")
        self.gridLayout_5.addWidget(self.again_pushButton_0_1, 1, 6, 1, 1)
        self.search_pushButton_0_1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_pushButton_0_1.sizePolicy().hasHeightForWidth())
        self.search_pushButton_0_1.setSizePolicy(sizePolicy)
        self.search_pushButton_0_1.setMinimumSize(QtCore.QSize(100, 30))
        self.search_pushButton_0_1.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.search_pushButton_0_1.setFont(font)
        self.search_pushButton_0_1.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color:#00ff7f;   \n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:10px;\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("D:/Projects/TrillionTech/images/search-13-64.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_pushButton_0_1.setIcon(icon11)
        self.search_pushButton_0_1.setIconSize(QtCore.QSize(20, 20))
        self.search_pushButton_0_1.setCheckable(False)
        self.search_pushButton_0_1.setAutoRepeat(False)
        self.search_pushButton_0_1.setAutoExclusive(False)
        self.search_pushButton_0_1.setObjectName("search_pushButton_0_1")
        self.gridLayout_5.addWidget(self.search_pushButton_0_1, 1, 7, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_2.setStyleSheet("background-color:  #fff8f2;\n"
"border-radius:5px;")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_25 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 10, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 0, 7, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 0, 8, 1, 1)
        self.refresh_pushButton_0_1 = QtWidgets.QPushButton(self.widget_2)
        self.refresh_pushButton_0_1.setEnabled(True)
        self.refresh_pushButton_0_1.setMinimumSize(QtCore.QSize(90, 23))
        self.refresh_pushButton_0_1.setMaximumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.refresh_pushButton_0_1.setFont(font)
        self.refresh_pushButton_0_1.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    border-width:1px;\n"
"    background-color:#ffe5cb;   \n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("D:/Projects/TrillionTech/images/sinchronize-64.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_pushButton_0_1.setIcon(icon12)
        self.refresh_pushButton_0_1.setCheckable(True)
        self.refresh_pushButton_0_1.setAutoExclusive(True)
        self.refresh_pushButton_0_1.setObjectName("refresh_pushButton_0_1")
        self.gridLayout_4.addWidget(self.refresh_pushButton_0_1, 0, 0, 1, 1)
        self.count_lineEdit_0_1 = QtWidgets.QLineEdit(self.widget_2)
        self.count_lineEdit_0_1.setEnabled(False)
        self.count_lineEdit_0_1.setObjectName("count_lineEdit_0_1")
        self.gridLayout_4.addWidget(self.count_lineEdit_0_1, 0, 11, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 0, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 0, 9, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 0, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 5, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 0, 3, 1, 1)
        self.tableWidget_0_1 = QtWidgets.QTableWidget(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.tableWidget_0_1.setFont(font)
        self.tableWidget_0_1.setStyleSheet("QHeaderView {\n"
"    border:0px;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"    border-radius:14px;\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    text-align:left;\n"
"\n"
"}\n"
"\n"
"QTableWidget::Item{\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    color: black;\n"
"}")
        self.tableWidget_0_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_0_1.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_0_1.setShowGrid(False)
        self.tableWidget_0_1.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_0_1.setWordWrap(True)
        self.tableWidget_0_1.setCornerButtonEnabled(False)
        self.tableWidget_0_1.setRowCount(2)
        self.tableWidget_0_1.setObjectName("tableWidget_0_1")
        self.tableWidget_0_1.setColumnCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_0_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_0_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_0_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_0_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_0_1.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_0_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_0_1.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_0_1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_0_1.setItem(1, 11, item)
        self.tableWidget_0_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_0_1.horizontalHeader().setDefaultSectionSize(105)
        self.tableWidget_0_1.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_0_1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_0_1.verticalHeader().setVisible(False)
        self.tableWidget_0_1.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_0_1.verticalHeader().setDefaultSectionSize(28)
        self.tableWidget_0_1.verticalHeader().setHighlightSections(False)
        self.tableWidget_0_1.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget_0_1.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableWidget_0_1, 2, 0, 1, 14)
        self.gridLayout_10.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 134))
        self.frame_3.setStyleSheet("QFrame {\n"
"    width: 100%;\n"
"    background:   #fff8f2;\n"
"    border-radius: 5px;\n"
"    padding-bottom: 13px;\n"
"    box-shadow: 1px 1px 3px rgb(0 0 0 / 20%);\n"
"    padding-top:15px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_14.setHorizontalSpacing(25)
        self.gridLayout_14.setVerticalSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setMaximumSize(QtCore.QSize(49, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 0, 5, 1, 1)
        self.in_dateEdit_1_1 = QtWidgets.QDateEdit(self.frame_3)
        self.in_dateEdit_1_1.setMinimumSize(QtCore.QSize(201, 31))
        self.in_dateEdit_1_1.setMaximumSize(QtCore.QSize(171, 16777215))
        self.in_dateEdit_1_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.in_dateEdit_1_1.setCalendarPopup(True)
        self.in_dateEdit_1_1.setObjectName("in_dateEdit_1_1")
        self.gridLayout_14.addWidget(self.in_dateEdit_1_1, 0, 2, 1, 1)
        self.search_pushButton_1_1 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_pushButton_1_1.sizePolicy().hasHeightForWidth())
        self.search_pushButton_1_1.setSizePolicy(sizePolicy)
        self.search_pushButton_1_1.setMinimumSize(QtCore.QSize(100, 30))
        self.search_pushButton_1_1.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.search_pushButton_1_1.setFont(font)
        self.search_pushButton_1_1.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color:#00ff7f;   \n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.search_pushButton_1_1.setIcon(icon11)
        self.search_pushButton_1_1.setIconSize(QtCore.QSize(20, 20))
        self.search_pushButton_1_1.setCheckable(False)
        self.search_pushButton_1_1.setAutoRepeat(False)
        self.search_pushButton_1_1.setAutoExclusive(False)
        self.search_pushButton_1_1.setObjectName("search_pushButton_1_1")
        self.gridLayout_14.addWidget(self.search_pushButton_1_1, 0, 8, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setMaximumSize(QtCore.QSize(101, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_14.addWidget(self.checkBox, 0, 1, 1, 1)
        self.supply_comboBox_1_1 = QtWidgets.QComboBox(self.frame_3)
        self.supply_comboBox_1_1.setMinimumSize(QtCore.QSize(201, 31))
        self.supply_comboBox_1_1.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.supply_comboBox_1_1.setFont(font)
        self.supply_comboBox_1_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.supply_comboBox_1_1.setEditable(True)
        self.supply_comboBox_1_1.setObjectName("supply_comboBox_1_1")
        self.gridLayout_14.addWidget(self.supply_comboBox_1_1, 0, 6, 1, 1)
        self.again_pushButton_1_1 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.again_pushButton_1_1.sizePolicy().hasHeightForWidth())
        self.again_pushButton_1_1.setSizePolicy(sizePolicy)
        self.again_pushButton_1_1.setMinimumSize(QtCore.QSize(100, 30))
        self.again_pushButton_1_1.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.again_pushButton_1_1.setFont(font)
        self.again_pushButton_1_1.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color:#ff6741;   \n"
"\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.again_pushButton_1_1.setIcon(icon10)
        self.again_pushButton_1_1.setIconSize(QtCore.QSize(20, 20))
        self.again_pushButton_1_1.setCheckable(False)
        self.again_pushButton_1_1.setAutoRepeat(False)
        self.again_pushButton_1_1.setAutoExclusive(False)
        self.again_pushButton_1_1.setObjectName("again_pushButton_1_1")
        self.gridLayout_14.addWidget(self.again_pushButton_1_1, 0, 7, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem18, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setMaximumSize(QtCore.QSize(77, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 0, 3, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem19, 0, 9, 1, 1)
        self.lot_num_comboBox_1_1 = QtWidgets.QComboBox(self.frame_3)
        self.lot_num_comboBox_1_1.setMinimumSize(QtCore.QSize(201, 31))
        self.lot_num_comboBox_1_1.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.lot_num_comboBox_1_1.setFont(font)
        self.lot_num_comboBox_1_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.lot_num_comboBox_1_1.setEditable(True)
        self.lot_num_comboBox_1_1.setObjectName("lot_num_comboBox_1_1")
        self.gridLayout_14.addWidget(self.lot_num_comboBox_1_1, 0, 4, 1, 1)
        self.in_dateEdit_1_1.raise_()
        self.label_17.raise_()
        self.again_pushButton_1_1.raise_()
        self.label_23.raise_()
        self.search_pushButton_1_1.raise_()
        self.supply_comboBox_1_1.raise_()
        self.lot_num_comboBox_1_1.raise_()
        self.checkBox.raise_()
        self.gridLayout_6.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.widget_4 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_4.setStyleSheet("background-color:  #fff8f2;\n"
"border-radius:5px;")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem20, 0, 5, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem21, 0, 4, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem22, 0, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem23, 0, 6, 1, 1)
        self.tableWidget_1_1 = QtWidgets.QTableWidget(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.tableWidget_1_1.setFont(font)
        self.tableWidget_1_1.setStyleSheet("QHeaderView {\n"
"    border:0px;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"    border-radius:14px;\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    text-align:left;\n"
"\n"
"}\n"
"\n"
"QTableWidget::Item{\n"
"    border-bottom:1px solid #d0c6ff;\n"
"}")
        self.tableWidget_1_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_1_1.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_1_1.setShowGrid(False)
        self.tableWidget_1_1.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_1_1.setWordWrap(True)
        self.tableWidget_1_1.setCornerButtonEnabled(False)
        self.tableWidget_1_1.setRowCount(2)
        self.tableWidget_1_1.setObjectName("tableWidget_1_1")
        self.tableWidget_1_1.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_1_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_1_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_1_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_1_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_1_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_1_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_1_1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1_1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1_1.setItem(1, 0, item)
        self.tableWidget_1_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_1_1.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_1_1.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_1_1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_1_1.verticalHeader().setVisible(False)
        self.tableWidget_1_1.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_1_1.verticalHeader().setDefaultSectionSize(28)
        self.tableWidget_1_1.verticalHeader().setHighlightSections(False)
        self.tableWidget_1_1.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget_1_1.verticalHeader().setStretchLastSection(False)
        self.gridLayout_13.addWidget(self.tableWidget_1_1, 1, 0, 1, 14)
        self.refresh_pushButton_1_1 = QtWidgets.QPushButton(self.widget_4)
        self.refresh_pushButton_1_1.setEnabled(True)
        self.refresh_pushButton_1_1.setMinimumSize(QtCore.QSize(90, 23))
        self.refresh_pushButton_1_1.setMaximumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.refresh_pushButton_1_1.setFont(font)
        self.refresh_pushButton_1_1.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    border-width:1px;\n"
"    background-color:#ffe5cb;  \n"
"    height:25px; \n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        self.refresh_pushButton_1_1.setIcon(icon12)
        self.refresh_pushButton_1_1.setCheckable(True)
        self.refresh_pushButton_1_1.setAutoExclusive(True)
        self.refresh_pushButton_1_1.setObjectName("refresh_pushButton_1_1")
        self.gridLayout_13.addWidget(self.refresh_pushButton_1_1, 0, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem24, 0, 8, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem25, 0, 9, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem26, 0, 7, 1, 1)
        self.count_lineEdit_1_1 = QtWidgets.QLineEdit(self.widget_4)
        self.count_lineEdit_1_1.setEnabled(False)
        self.count_lineEdit_1_1.setObjectName("count_lineEdit_1_1")
        self.gridLayout_13.addWidget(self.count_lineEdit_1_1, 0, 12, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem27, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 0, 11, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem28, 0, 2, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem29, 0, 10, 1, 1)
        self.gridLayout_15.addWidget(self.widget_4, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_7.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "售后管理软件"))
        self.label.setText(_translate("MainWindow", "导航栏"))
        self.CheckCountPB.setText(_translate("MainWindow", " 创建统计单"))
        self.ProductSearchPB.setText(_translate("MainWindow", " 查询统计单"))
        self.ProductSearchPB_2.setText(_translate("MainWindow", " 查询入库单"))
        self.groupBox_3.setTitle(_translate("MainWindow", "手机信息栏"))
        self.label_4.setText(_translate("MainWindow", "不良项："))
        self.label_27.setText(_translate("MainWindow", "手机机型："))
        self.pushButton_3.setText(_translate("MainWindow", "获取手机信息"))
        self.label_11.setText(_translate("MainWindow", "申请金额："))
        self.label_18.setText(_translate("MainWindow", "处理方式："))
        self.label_10.setText(_translate("MainWindow", "导入文件："))
        self.label_5.setText(_translate("MainWindow", "手机内存："))
        self.pushButton_7.setText(_translate("MainWindow", "导入文件"))
        self.label_22.setText(_translate("MainWindow", "上报总数："))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IEMI"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "机型"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "内存"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "不良项"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "处理方式"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "申请金额"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "备注"))
        self.label_28.setText(_translate("MainWindow", "备注："))
        self.pushButton_5.setText(_translate("MainWindow", "创建统计单"))
        self.groupBox_2.setTitle(_translate("MainWindow", "统计单信息"))
        self.label_15.setText(_translate("MainWindow", "创建时间："))
        self.label_14.setText(_translate("MainWindow", "责任人："))
        self.label_16.setText(_translate("MainWindow", "Case Num："))
        self.pushButton_2.setText(_translate("MainWindow", "创建Case Num"))
        self.pushButton_4.setText(_translate("MainWindow", "创建统计单"))
        self.groupBox.setTitle(_translate("MainWindow", "入库单信息"))
        self.label_13.setText(_translate("MainWindow", "手机机型："))
        self.label_6.setText(_translate("MainWindow", "供应商："))
        self.label_12.setText(_translate("MainWindow", "到货数量："))
        self.label_3.setText(_translate("MainWindow", "Lot Num："))
        self.label_20.setText(_translate("MainWindow", "手机内存："))
        self.label_19.setText(_translate("MainWindow", "到货时间："))
        self.pushButton.setText(_translate("MainWindow", " 添加机型列表"))
        self.label_7.setText(_translate("MainWindow", "发票号："))
        self.pushButton_6.setText(_translate("MainWindow", "清空列表"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "机型"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "内存"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "数量"))
        self.groupBox_4.setTitle(_translate("MainWindow", "搜索栏"))
        self.checkBox_2.setText(_translate("MainWindow", "创建时间："))
        self.label_8.setText(_translate("MainWindow", "供应商："))
        self.label_26.setText(_translate("MainWindow", "IMEI："))
        self.label_21.setText(_translate("MainWindow", "Lot Num："))
        self.label_9.setText(_translate("MainWindow", "状态："))
        self.again_pushButton_0_1.setText(_translate("MainWindow", "重置"))
        self.search_pushButton_0_1.setText(_translate("MainWindow", "搜索"))
        self.groupBox_5.setTitle(_translate("MainWindow", "显示栏"))
        self.label_25.setText(_translate("MainWindow", "总数："))
        self.refresh_pushButton_0_1.setText(_translate("MainWindow", "刷新"))
        self.tableWidget_0_1.setSortingEnabled(True)
        item = self.tableWidget_0_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_0_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_0_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", " Case Num"))
        item = self.tableWidget_0_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "到货时间"))
        item = self.tableWidget_0_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "创建时间"))
        item = self.tableWidget_0_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Lot Num"))
        item = self.tableWidget_0_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "供应商"))
        item = self.tableWidget_0_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "不良数"))
        item = self.tableWidget_0_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "不良率"))
        item = self.tableWidget_0_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "RMA Num"))
        item = self.tableWidget_0_1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "退货单号"))
        item = self.tableWidget_0_1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableWidget_0_1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "责任人"))
        item = self.tableWidget_0_1.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "操作"))
        __sortingEnabled = self.tableWidget_0_1.isSortingEnabled()
        self.tableWidget_0_1.setSortingEnabled(False)
        item = self.tableWidget_0_1.item(0, 0)
        item.setText(_translate("MainWindow", "20210225001"))
        item = self.tableWidget_0_1.item(0, 11)
        item.setText(_translate("MainWindow", "详情"))
        item = self.tableWidget_0_1.item(1, 0)
        item.setText(_translate("MainWindow", "20210225002"))
        item = self.tableWidget_0_1.item(1, 11)
        item.setText(_translate("MainWindow", "详情"))
        self.tableWidget_0_1.setSortingEnabled(__sortingEnabled)
        self.groupBox_6.setTitle(_translate("MainWindow", "搜索栏"))
        self.label_17.setText(_translate("MainWindow", "供应商："))
        self.search_pushButton_1_1.setText(_translate("MainWindow", "搜索"))
        self.checkBox.setText(_translate("MainWindow", "到货时间："))
        self.again_pushButton_1_1.setText(_translate("MainWindow", "重置"))
        self.label_23.setText(_translate("MainWindow", "Lot Num："))
        self.groupBox_7.setTitle(_translate("MainWindow", "显示栏"))
        self.tableWidget_1_1.setSortingEnabled(True)
        item = self.tableWidget_1_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_1_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_1_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", " Lot Num"))
        item = self.tableWidget_1_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "到货时间"))
        item = self.tableWidget_1_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "供应商"))
        item = self.tableWidget_1_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "发票号"))
        item = self.tableWidget_1_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "机型"))
        item = self.tableWidget_1_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "内存"))
        item = self.tableWidget_1_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "到货数量"))
        item = self.tableWidget_1_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "操作"))
        __sortingEnabled = self.tableWidget_1_1.isSortingEnabled()
        self.tableWidget_1_1.setSortingEnabled(False)
        self.tableWidget_1_1.setSortingEnabled(__sortingEnabled)
        self.refresh_pushButton_1_1.setText(_translate("MainWindow", "刷新"))
        self.label_24.setText(_translate("MainWindow", "总数："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
