# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\update_case.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1556, 802)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../AfterSale/static/img/available-updates-256.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_2.setStyleSheet("QFrame {\n"
"    width: 100%;\n"
"    background:   #fff8f2;\n"
"    border-radius: 5px;\n"
"    padding-bottom: 13px;\n"
"    box-shadow: 1px 1px 3px rgb(0 0 0 / 20%);\n"
"    padding-top:15px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setHorizontalSpacing(28)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.credit_lineEdit_1_6 = QtWidgets.QLineEdit(self.frame_2)
        self.credit_lineEdit_1_6.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_6.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_6.setFont(font)
        self.credit_lineEdit_1_6.setObjectName("credit_lineEdit_1_6")
        self.gridLayout_2.addWidget(self.credit_lineEdit_1_6, 1, 6, 1, 1)
        self.type_comboBox_1_1 = QtWidgets.QComboBox(self.frame_2)
        self.type_comboBox_1_1.setMinimumSize(QtCore.QSize(200, 30))
        self.type_comboBox_1_1.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.type_comboBox_1_1.setFont(font)
        self.type_comboBox_1_1.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.type_comboBox_1_1.setEditable(True)
        self.type_comboBox_1_1.setObjectName("type_comboBox_1_1")
        self.gridLayout_2.addWidget(self.type_comboBox_1_1, 1, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background:   #fff8f2;")
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 1, 5, 1, 1)
        self.credit_lineEdit_1_4 = QtWidgets.QLineEdit(self.frame_2)
        self.credit_lineEdit_1_4.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_4.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_4.setFont(font)
        self.credit_lineEdit_1_4.setObjectName("credit_lineEdit_1_4")
        self.gridLayout_2.addWidget(self.credit_lineEdit_1_4, 2, 2, 1, 1)
        self.credit_lineEdit_1_5 = QtWidgets.QLineEdit(self.frame_2)
        self.credit_lineEdit_1_5.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_5.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_5.setFont(font)
        self.credit_lineEdit_1_5.setText("")
        self.credit_lineEdit_1_5.setObjectName("credit_lineEdit_1_5")
        self.gridLayout_2.addWidget(self.credit_lineEdit_1_5, 2, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 10, 1, 1)
        self.change_pushButton_0_2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_pushButton_0_2.sizePolicy().hasHeightForWidth())
        self.change_pushButton_0_2.setSizePolicy(sizePolicy)
        self.change_pushButton_0_2.setMinimumSize(QtCore.QSize(100, 30))
        self.change_pushButton_0_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.change_pushButton_0_2.setFont(font)
        self.change_pushButton_0_2.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color:#00ff7f;   \n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:10px;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/Projects/TrillionTech/images/sinchronize-64.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_pushButton_0_2.setIcon(icon1)
        self.change_pushButton_0_2.setIconSize(QtCore.QSize(20, 20))
        self.change_pushButton_0_2.setCheckable(False)
        self.change_pushButton_0_2.setAutoRepeat(False)
        self.change_pushButton_0_2.setAutoExclusive(False)
        self.change_pushButton_0_2.setAutoDefault(False)
        self.change_pushButton_0_2.setObjectName("change_pushButton_0_2")
        self.gridLayout_2.addWidget(self.change_pushButton_0_2, 2, 9, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background:   #fff8f2;")
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 2, 3, 1, 1)
        self.credit_lineEdit_1_7 = QtWidgets.QLineEdit(self.frame_2)
        self.credit_lineEdit_1_7.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_7.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_7.setFont(font)
        self.credit_lineEdit_1_7.setText("")
        self.credit_lineEdit_1_7.setObjectName("credit_lineEdit_1_7")
        self.gridLayout_2.addWidget(self.credit_lineEdit_1_7, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:   #fff8f2;")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background:   #fff8f2;")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(120, 28))
        self.pushButton_7.setMaximumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#5cb0ff;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../../AfterSale/static/img/excel-3-64.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 2, 7, 1, 1)
        self.again_pushButton_0_2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.again_pushButton_0_2.sizePolicy().hasHeightForWidth())
        self.again_pushButton_0_2.setSizePolicy(sizePolicy)
        self.again_pushButton_0_2.setMinimumSize(QtCore.QSize(100, 30))
        self.again_pushButton_0_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.again_pushButton_0_2.setFont(font)
        self.again_pushButton_0_2.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color:#ff6741;   \n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00aaff;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:10px;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:/Projects/TrillionTech/images/redo-2-128.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.again_pushButton_0_2.setIcon(icon3)
        self.again_pushButton_0_2.setIconSize(QtCore.QSize(20, 20))
        self.again_pushButton_0_2.setCheckable(False)
        self.again_pushButton_0_2.setAutoRepeat(False)
        self.again_pushButton_0_2.setAutoExclusive(False)
        self.again_pushButton_0_2.setAutoDefault(False)
        self.again_pushButton_0_2.setObjectName("again_pushButton_0_2")
        self.gridLayout_2.addWidget(self.again_pushButton_0_2, 1, 9, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.credit_lineEdit_1_2 = QtWidgets.QLineEdit(self.frame_2)
        self.credit_lineEdit_1_2.setEnabled(False)
        self.credit_lineEdit_1_2.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_2.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_2.setFont(font)
        self.credit_lineEdit_1_2.setObjectName("credit_lineEdit_1_2")
        self.gridLayout_2.addWidget(self.credit_lineEdit_1_2, 2, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background:   #fff8f2;")
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setStyleSheet("background-color:  #fff8f2;\n"
"border-radius:5px;")
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(710, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 6, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background:   #fff8f2;")
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 7, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(135, 0))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(135, 16777215))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    border-style: solid;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-width:1px;\n"
"    border-radius:1px;\n"
"}")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.plainTextEdit)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(49, 20))
        self.label_2.setMaximumSize(QtCore.QSize(49, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:   #fff8f2;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMaximumSize(QtCore.QSize(64, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.gridLayout_7.addLayout(self.formLayout, 1, 10, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(90, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    border-width:1px;\n"
"    background-color:#aaffff;   \n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\../static/img/edit-property-128.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 3, 1, 1)
        self.credit_lineEdit_1_8 = QtWidgets.QLineEdit(self.widget)
        self.credit_lineEdit_1_8.setEnabled(False)
        self.credit_lineEdit_1_8.setMinimumSize(QtCore.QSize(100, 30))
        self.credit_lineEdit_1_8.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_8.setFont(font)
        self.credit_lineEdit_1_8.setStyleSheet("")
        self.credit_lineEdit_1_8.setObjectName("credit_lineEdit_1_8")
        self.gridLayout_7.addWidget(self.credit_lineEdit_1_8, 0, 8, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setMinimumSize(QtCore.QSize(1351, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView {\n"
"    border:0px;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"    border-radius:14px;\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    text-align:left;\n"
"\n"
"}\n"
"\n"
"QTableWidget::Item{\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    color: black;\n"
"}")
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(131)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tableWidget, 1, 1, 1, 9)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_8.setMaximumSize(QtCore.QSize(90, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#5cb0ff;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\../static/img/arrow-96-48.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_7.addWidget(self.pushButton_8, 0, 4, 1, 1)
        self.refresh_pushButton_0_1 = QtWidgets.QPushButton(self.widget)
        self.refresh_pushButton_0_1.setEnabled(True)
        self.refresh_pushButton_0_1.setMinimumSize(QtCore.QSize(90, 23))
        self.refresh_pushButton_0_1.setMaximumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.refresh_pushButton_0_1.setFont(font)
        self.refresh_pushButton_0_1.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    border-width:1px;\n"
"    background-color:#ffe5cb;   \n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        self.refresh_pushButton_0_1.setIcon(icon1)
        self.refresh_pushButton_0_1.setCheckable(True)
        self.refresh_pushButton_0_1.setAutoExclusive(True)
        self.refresh_pushButton_0_1.setAutoDefault(False)
        self.refresh_pushButton_0_1.setObjectName("refresh_pushButton_0_1")
        self.gridLayout_7.addWidget(self.refresh_pushButton_0_1, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_9.setMaximumSize(QtCore.QSize(90, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom: 5px;\n"
"    background-color:#fff8f2;\n"
"    border-color:#929799;\n"
"    border-style:solid;\n"
"    border-width:0.5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#00ff7f;   \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:15px;\n"
"    border-radius:5px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\../static/img/x-mark-64.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_7.addWidget(self.pushButton_9, 0, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 0, 1, 1)
        self.credit_lineEdit_1_3 = QtWidgets.QLineEdit(self.widget)
        self.credit_lineEdit_1_3.setEnabled(False)
        self.credit_lineEdit_1_3.setMinimumSize(QtCore.QSize(100, 30))
        self.credit_lineEdit_1_3.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_3.setFont(font)
        self.credit_lineEdit_1_3.setStyleSheet("")
        self.credit_lineEdit_1_3.setObjectName("credit_lineEdit_1_3")
        self.gridLayout_7.addWidget(self.credit_lineEdit_1_3, 0, 10, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_7.addWidget(self.checkBox, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background:   #fff8f2;")
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 9, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 11, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 183))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setStyleSheet("QFrame {\n"
"    width: 100%;\n"
"    background:   #fff8f2;\n"
"    border-radius: 5px;\n"
"    padding-bottom: 13px;\n"
"    box-shadow: 1px 1px 3px rgb(0 0 0 / 20%);\n"
"    padding-top:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(15)
        self.gridLayout_4.setVerticalSpacing(20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setMaximumSize(QtCore.QSize(101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 2, 1, 1)
        self.RMA_num_lineEdit_0_2 = QtWidgets.QLineEdit(self.frame)
        self.RMA_num_lineEdit_0_2.setEnabled(True)
        self.RMA_num_lineEdit_0_2.setMinimumSize(QtCore.QSize(201, 31))
        self.RMA_num_lineEdit_0_2.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.RMA_num_lineEdit_0_2.setFont(font)
        self.RMA_num_lineEdit_0_2.setObjectName("RMA_num_lineEdit_0_2")
        self.gridLayout_4.addWidget(self.RMA_num_lineEdit_0_2, 1, 3, 1, 1)
        self.in_dateEdit_1_0 = QtWidgets.QDateEdit(self.frame)
        self.in_dateEdit_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.in_dateEdit_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.in_dateEdit_1_0.setFont(font)
        self.in_dateEdit_1_0.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.in_dateEdit_1_0.setWrapping(False)
        self.in_dateEdit_1_0.setFrame(True)
        self.in_dateEdit_1_0.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.in_dateEdit_1_0.setAccelerated(True)
        self.in_dateEdit_1_0.setProperty("showGroupSeparator", True)
        self.in_dateEdit_1_0.setCalendarPopup(True)
        self.in_dateEdit_1_0.setObjectName("in_dateEdit_1_0")
        self.gridLayout_4.addWidget(self.in_dateEdit_1_0, 0, 1, 1, 1)
        self.credit_lineEdit_1_1 = QtWidgets.QLineEdit(self.frame)
        self.credit_lineEdit_1_1.setEnabled(False)
        self.credit_lineEdit_1_1.setMinimumSize(QtCore.QSize(200, 30))
        self.credit_lineEdit_1_1.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.credit_lineEdit_1_1.setFont(font)
        self.credit_lineEdit_1_1.setObjectName("credit_lineEdit_1_1")
        self.gridLayout_4.addWidget(self.credit_lineEdit_1_1, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setMaximumSize(QtCore.QSize(130, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background:   #fff8f2;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setMaximumSize(QtCore.QSize(101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 4, 1, 1)
        self.lot_num_lineEdit_1_0 = QtWidgets.QLineEdit(self.frame)
        self.lot_num_lineEdit_1_0.setEnabled(False)
        self.lot_num_lineEdit_1_0.setMinimumSize(QtCore.QSize(200, 30))
        self.lot_num_lineEdit_1_0.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.lot_num_lineEdit_1_0.setFont(font)
        self.lot_num_lineEdit_1_0.setObjectName("lot_num_lineEdit_1_0")
        self.gridLayout_4.addWidget(self.lot_num_lineEdit_1_0, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setMaximumSize(QtCore.QSize(49, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.return_lineEdit_0_2 = QtWidgets.QLineEdit(self.frame)
        self.return_lineEdit_0_2.setEnabled(True)
        self.return_lineEdit_0_2.setMinimumSize(QtCore.QSize(201, 31))
        self.return_lineEdit_0_2.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.return_lineEdit_0_2.setFont(font)
        self.return_lineEdit_0_2.setObjectName("return_lineEdit_0_2")
        self.gridLayout_4.addWidget(self.return_lineEdit_0_2, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(130, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:   #fff8f2;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background:   #fff8f2;\n"
" ")
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 2, 1, 1)
        self.status_comboBox_0_2 = QtWidgets.QComboBox(self.frame)
        self.status_comboBox_0_2.setMinimumSize(QtCore.QSize(201, 31))
        self.status_comboBox_0_2.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.status_comboBox_0_2.setFont(font)
        self.status_comboBox_0_2.setStyleSheet("QComboBox{\n"
"    font-family:\"黑体\", Times, serif;\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.status_comboBox_0_2.setEditable(True)
        self.status_comboBox_0_2.setObjectName("status_comboBox_0_2")
        self.gridLayout_4.addWidget(self.status_comboBox_0_2, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "修改统计单"))
        self.groupBox_2.setTitle(_translate("Dialog", "手机信息栏"))
        self.label_29.setText(_translate("Dialog", "备注："))
        self.change_pushButton_0_2.setText(_translate("Dialog", "修改"))
        self.label_28.setText(_translate("Dialog", "IEMI："))
        self.label.setText(_translate("Dialog", "处理进度："))
        self.label_10.setText(_translate("Dialog", "导入文件："))
        self.label_12.setText(_translate("Dialog", "审批金额："))
        self.pushButton_7.setText(_translate("Dialog", "导入文件"))
        self.again_pushButton_0_2.setText(_translate("Dialog", "重置"))
        self.label_21.setText(_translate("Dialog", "处理方式："))
        self.label_23.setText(_translate("Dialog", "已选择："))
        self.label_2.setText(_translate("Dialog", " 总数："))
        self.pushButton.setText(_translate("Dialog", "更新数据"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "   IEMI"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "机型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "内存"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "不良项"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "处理方式"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "处理进度"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "修改时间"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "申请金额"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "审批金额"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "备注"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "888"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "999"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_8.setText(_translate("Dialog", "录入"))
        self.refresh_pushButton_0_1.setText(_translate("Dialog", "刷新"))
        self.pushButton_9.setText(_translate("Dialog", "清空"))
        self.checkBox.setText(_translate("Dialog", "全选"))
        self.label_22.setText(_translate("Dialog", "总数："))
        self.groupBox.setTitle(_translate("Dialog", "基本信息栏"))
        self.label_18.setText(_translate("Dialog", "RMA Num："))
        self.label_19.setText(_translate("Dialog", "修改时间："))
        self.label_20.setText(_translate("Dialog", "退货单号："))
        self.label_11.setText(_translate("Dialog", "状态："))
        self.label_3.setText(_translate("Dialog", "Lot Num："))
        self.label_16.setText(_translate("Dialog", "Case Num："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
